[project]
name = "pacman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arcade>=3.3.3",
    "mazegenerator",
    "rich>=15.0.0",
]

[tool.uv.sources]
mazegenerator = { path = "wheels/mazegenerator-2.0.2-py3-none-any.whl" }
